[package]
name = "krystallizer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
figment = { version = "0.10.19", features = ["toml", "env"] }
futures = "0.3.31"
indexmap = { version = "2.12.0", features = ["serde"] }
llm = { version = "1.3.4", features = ["agent", "anthropic", "api", "google", "logging", "ollama", "openai"] }
reqwest = { version = "0.12.24", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.145"
surrealdb = "2.3.10"
tokio = "1.48.0"

[lib]
name = "krystallizer"
path = "src/libs/mod.rs"

[[bin]]
name = "core"
path = "src/main.rs"

[[bin]]
name = "init"
path = "src/init.rs"
