[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
figment = { version = "0.10.19", features = ["toml", "env"] }
futures = "0.3.31"
indexmap = { version = "2.12.1", features = ["serde"] }
llm = { version = "1.3.6", features = ["agent", "anthropic", "api", "google", "logging", "ollama", "openai"] }
regex = "1.12.2"
reqwest = { version = "0.12.24", features = ["json"] }
rmcp = "0.9.0"
serde = "1.0.228"
serde_json = "1.0.145"
surrealdb = "2.3.10"
tokio = "1.48.0"

[lib]
name = "core"
path = "src/libs/mod.rs"
