[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
figment = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
llm = { version = "1.3.6", features = ["agent", "anthropic", "api", "google", "logging", "ollama", "openai"] }
rmcp = "0.9.1"
surrealdb = "2.4.0"
rune = { workspace = true, optional = true }
minijinja = { workspace = true }
wasmtime = { workspace = true, features = ["std"] }

[features]
script = ["dep:rune"]

[lib]
name = "core"
path = "src/libs/mod.rs"
